### ISSUE TITLE
Устранение недочётов

### ISSUE THREAD

**Issue by mvaload** [cusodede/yii2-s3-module#29]
1) Таблица выходит за пределы поля:

<img width="858" alt="screenshot_1" src="https://user-images.githubusercontent.com/24808041/164654301-8c78876c-8ae9-49ed-a26e-7c805e1e8028.png">
2) Ошибка при создании и изменении файла без тега :

<img width="385" alt="screenshot_2" src="https://user-images.githubusercontent.com/24808041/164655638-27b374c3-8e49-454c-ab1b-a145172fbe27.png">
3) При загрузке другого файла не меняется название файла:

<img width="1239" alt="screenshot_3" src="https://user-images.githubusercontent.com/24808041/164655824-4bf33bbf-773a-466a-9235-88e027b1caca.png">
4) При выгрузке файла из view ошибка Страница не найдена :

<img width="358" alt="screenshot_4" src="https://user-images.githubusercontent.com/24808041/164656047-ede7384d-c4b5-4e2f-b124-566e0503bbb4.png">

**Comment by pozitronik** [comment]
По п.1. - это дефолтная вьюха, можно написать свою, и подсунуть её через конфиг.

**Comment by pozitronik** [comment]
>При загрузке другого файла не меняется название файла: 

Так и задумано. Ссылка и название файла остаются прежние, редактируется его содержимое.

Закрываю, часть изменений черрипикнул, часть поправил сам.
