### ISSUE TITLE
Ошибка при загрузке файла используя метод uploadFileFromModel

### ISSUE THREAD

**Issue by s1lver** [cusodede/yii2-s3-module#38]
При попытке загрузки файла с использованием метода `uploadFileFromModel` получаем ошибку:
> Setting read-only property: cusodede\s3\models\cloud_storage\CloudStorage::instance

 Проблема заключается в не корректном использовании атрибута модели
```php
[
    'instance' => $connection
]
```

**Comment by pozitronik** [comment]
Ну раз ты знаешь, в чём проблема, так, может, и запатчишь?
