### ISSUE TITLE
bugs 

### ISSUE THREAD

**Issue by antonshevelev** [cusodede/yii2-s3-module#4]
1) `S3Helper::FileToStorage` не учитывает то что названия файла может не быть и в `$filePath` и `$fileName`.
Предлогаю решение:
<img width="1057" alt="Снимок экрана 2022-03-29 в 17 57 19" src="https://user-images.githubusercontent.com/10631259/160641354-1794a8f7-7a2b-4ec3-9c9d-ecad6c97fe66.png">
2) `S3::saveObject` не сохраняет раcширение. Из-за этого, например, падает парсер xlsx.
Предлогаю решение: добавить строку, как было до вынесения в модуль `$key = implode('_', [Yii::$app->security->generateRandomString(), $fileName]);`
<img width="923" alt="Снимок экрана 2022-03-29 в 18 01 09" src="https://user-images.githubusercontent.com/10631259/160642353-d3ba1bf6-b20b-4377-ab59-6c30005b9f92.png">

**Comment by pozitronik** [comment]
Оформляй PR.
